### ISSUE TITLE
Change request

### ISSUE THREAD

**Issue by smartbyte** [joostlek/python-opensky#71]
First of all, I like to state that I highly respect the time and effort which has flown into this integration.
I personally think it is 100%, very good, and I am aware that this request is pretty cheeky, but never the less I think plenty of people will benefit from the following changes, and as I cannot do them myself, I am asking a lot here. :-(

I am not a *Python* Developer, but I can read and write code...

When I read your code it states that the refresh interval is 15 Minutes, which is 100% correct for "the blank case",
But looking at the Opensky website: https://openskynetwork.github.io/opensky-api/rest.html#api-credit-usage
It states that for requests under 500km radius, they only charge 1 credit (Interval=216 seconds only).
Could we make the scan interval dependant on the radius, or enter the scan interval as a parameter that can be user defined?

Next thing:
If the user has a name and password with opensky, she or he can get 4000 to 8000 credits.
Could we integrate something, so we are able to pass username and password as a parameter and based on that change the scan interval is recalculated, or as stated above add a paramter scan_interval, so that the admin can define the interval in the HA config?

I am not expecting anything here, I am just asking, if you could look into this?

**Comment by joostlek** [comment]
Thanks for the message! I first need to add a config flow, after which I can check if we can (and are allowed to) use dynamic timing (so if someone has a really big radius, it wouldn't update as often as a smaller radius). I am not sure if this fits into the HA architecture. I think it's also a discussion to see if we still allow unauthenticated users to use it, or that we force everyone to use authentication.

But I know for sure, a scan interval set by config (via options or something) is unwanted, so we can't do that

**Comment by joostlek** [comment]
To give an update on this. Next HA release will feature the config flow for OpenSky, so we're a step further!

**Comment by coutadeurf** [comment]
Hi,

I modified a bit my local version of Opensky integration, to add you upcoming authentication code in __init__.py with my Opensky's user and password in it and I am able to refresh each 25s, without reaching the limit, which is awesome!

**Comment by joostlek** [comment]
You're welcome :)
